### PR TITLE
Hide more Youtube times

### PR DESCRIPTION
**Pull request by ranamit112**
Thanks for the great extension - here are some small fixes/enhancements

### CODE REVIEW

**Comment by krishmasand** [comment]
Sorry for the insanely long time it took for me to reply, but I'm actively monitoring this repo now. It seems like hiding the videowall times doesn't actually work. If it did in the past, I apologize, but feel free to fix this pull request now if you wish to - I'll accept it once you hide the videowall times :)

**Comment by ranamit112** [comment]
Hi, It's actually been a long time since I last used the extension, but I'm glad to have it updated.
I fixed the videowall (it was a class name change) and added some unpushed code I had:
1. CE class is for previews of videos inside videos.  
2. The reason for the *.youtube.com change is that youtube and twitch have subdomains (such as gaming.youtube.com) and the extension should work there as well.

**Comment by krishmasand** [comment]
Cool, thanks for your work!

**Comment by ranamit112** [comment]
I just noticed a bug in my merge of the manifest (I made it inside github) : the comma after "http://\*.twitch.tv/\*" is missing

**Comment by krishmasand** [comment]
Fixed in https://github.com/krishmasand/Anticipation-Chrome/commit/93ea7e6d9f79c37cfb380c3eb211f63e0e2d1b0b

**Comment by ranamit112** [comment]
Hi, could you release an updated version with my changes? (I assume with
version 1.0.7 or something)

**Comment by krishmasand** [comment]
Yeah, I'll probably cut a build either this weekend or next weekend :)

**Pull request merged**
